### ISSUE TITLE
Fuses missing

### ISSUE THREAD

**Issue by dg8ygz** [dg1yfe/mcmega#1]
No Fuses for the ATMEGA were documented
if there's any additional info needed it would be helpful to know

73s

**Comment by dg8ygz** [comment]
FUSES:
low:  **0xD4**
high: **0x10**
ext.:   **0xFF**

necessary:  
(in AVR Studio 7)
/Toolchain/AVR GNU Compiler/ Symbols/
**F_CPU=8000000**

/Toolchain/AVR GNU Compiler/Optimization/
**set level to Size   (Os)**
other Flags:
**-Ttext=0xF800**

then it should work with the programm adapter shown here with 8N1 19200

tnx to dg1yfe for info

**Comment by dg1yfe** [comment]
Bug and solution relates to https://github.com/dg1yfe/mcmboot/ .
